---
- name: Configure systemd resolved.conf
  become: yes
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    backup: yes
    mode: 0644
    owner: root
    group: root
  notify:
    - Reload systemd

- name: Configure resolv.conf
  become: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    backup: yes
    mode: 0644
    owner: root
    group: root

