---
- name: Install iptables
  package:
    update_cache: yes
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Enable iptables service
  systemd:
    name: iptables
    enabled: yes
    state: started

- name: Set default policy for FORWARD chain to DROP
  iptables:
    table: filter
    chain: FORWARD
    policy: DROP   

- name: Allow new incoming SYN packets on TCP port (SSH)
  iptables:
    table: filter
    chain: INPUT
    action: insert
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    syn: match
    jump: ACCEPT
    state: present
    comment: Accept new SSH connections.

- name: Allow icmp packets
  iptables:
    table: filter
    chain: INPUT
    action: insert
    protocol: icmp
    jump: ACCEPT
    state: present
    comment: Accept ICMP packets.

- name: Allow all loopback interface packets
  iptables:
    table: filter
    chain: INPUT
    action: insert
    in_interface: lo
    jump: ACCEPT
    state: present
    comment: Allow loopback interface packets.

- name: Allow incoming related and established connections
  iptables:
    table: filter
    chain: INPUT
    action: insert
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present
    comment: Allow incoming related and established connections.

- name: Allow all outgoing related and established connections.
  iptables:
    table: filter
    chain: OUTPUT
    action: insert
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present
    comment: Allow outgoing related and established connections.

- name: Drop all other packets
  iptables:
    table: filter
    chain: INPUT
    action: append
    jump: DROP
    state: present
    comment: Drop all other packets.

- name: Allow http and https ports
  iptables:
    table: filter
    chain: INPUT
    action: insert
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
    jump: ACCEPT
    state: present
    comment: Allow http and https ports.

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  notify: Restart iptables

